---
title: "Performance phases"
author: "Pierre Donat-Bouillud"
date: "2023-06-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(readr)
library(stringr)
library(ggplot2)
library(forcats)
library(DT)

here::i_am("analysis/perf-phases.Rmd")

library(here)
```

## Data loading

```{r}
profiles <- read_csv(here("artifacts/results/benchmark_dir-profiles/profiles.csv"))
```

## Basic analysis

```{r}
mean_pc <- summarize(profiles, across(ends_with("-pc"), mean)) %>% unlist %>%
sort(decreasing=TRUE) %>% 
  tibble::enframe(name = "Phase", value = "AvgPc") %>%
  mutate(Phase = str_extract(Phase, "([^-])*"))  # remove the ugly -pc suffix
mean_pc %>%  knitr::kable(digits = 1)
```


```{r, fig.width=8, fig.height=9}
ggplot(mean_pc) +
  geom_col(aes(x=fct_reorder(Phase, AvgPc), y=AvgPc)) +
  coord_flip() +
  labs(y="%")
```

## Weighted rank aggregation


Let's do it more correctly using [weighted rank aggregation](https://cran.r-project.org/web/packages/RankAggreg/vignettes/RankAggreg.pdf):

```{r}
library(RankAggreg) 

# create a matrix of the phases ranked by increasing order of pc 
ranks_df <- select(profiles, ends_with("-pc"))

ranks <- matrix("", nrow = nrow(ranks_df), ncol = length(ranks_df), byrow=TRUE)
percents <- matrix(0, nrow = nrow(ranks_df), ncol = length(ranks_df), byrow=TRUE)

ranks <- apply(ranks_df, 1, function(row) {
  unlist(row) %>% sort(decreasing=TRUE) %>% names()
}) %>% t() # need to transpose!

percents <-  apply(ranks_df, 1, function(row) {
  unlist(row) %>% sort(decreasing=TRUE)
}) %>% t() # need to transpose!
# TODO: we should do both at the same time...

```

We first get the ranks of all the phases for each sample. The weights are the percentages.
```{r}
datatable(ranks)
```

Now, we can compute the weighted rank aggregation:

```{r}
ranked <- RankAggreg(ranks, ncol(ranks), percents, "CE", "Spearman", seed = 745)
```


